# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            圣托马斯
tagline:          一个程序员
url:              http://blog.utopia-project.com
paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ibusybox/blog

pages_list: 
  About: '/about'
  My Baby: 'http://www.maozheyang.com'
  RSS: '/atom.xml'
  TekTea: 'http://tektea.com'
