# Dependencies
#markdown_ext: 	  foo
#markdown:         redcarpet
markdown: 		  kramdown
#pygments:         true
highlighter:   pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            圣托马斯
tagline:          一个程序员
url:              http://blog.utopia-project.com
paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ibusybox/blog

pages_list: 
  #My Baby: 'http://www.maozheyang.com'
  运维派: 'http://www.yunweipai.com'
  Archive: '/archive'
  About: '/about'
  RSS: '/atom.xml'
